package com.example.ui.utils

object Quotes {
    val list = listOf(
        Pair("Focus on being productive instead of busy.", "Tim Ferriss"),
        Pair("Your mind is for having ideas, not holding them.", "David Allen"),
        Pair("The secret of getting ahead is getting started.", "Mark Twain"),
        Pair("Yesterday is history, tomorrow is a mystery, today is a gift.", "Eleanor Roosevelt"),
        Pair("You do not rise to the level of your goals. You fall to the level of your systems.", "James Clear"),
        Pair("The best way to predict the future is to create it.", "Peter Drucker"),
        Pair("Simplicity is the ultimate sophistication.", "Leonardo da Vinci"),
        Pair("Productivity is never an accident. It is always the result of a commitment to excellence, intelligent planning, and focused effort.", "Paul J. Meyer"),
        Pair("Action is the foundational key to all success.", "Pablo Picasso"),
        Pair("The way to get started is to quit talking and begin doing.", "Walt Disney"),
        Pair("Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", "Stephen King"),
        Pair("Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.", "Alexander Graham Bell"),
        Pair("Until we can manage time, we can manage nothing else.", "Peter Drucker"),
        Pair("Great things are done by a series of small things brought together.", "Vincent Van Gogh"),
        Pair("It is not that we have a short time to live, but that we waste a lot of it.", "Seneca"),
        Pair("Deciding what not to do is as important as deciding what to do.", "Jessica Jackley"),
        Pair("The key is not to prioritize what's on your schedule, but to schedule your priorities.", "Stephen Covey"),
        Pair("If you spend too much time thinking about a thing, you'll never get it done.", "Bruce Lee"),
        Pair("Infinite striving to be the best is man's duty; it is its own reward.", "Mahatma Gandhi"),
        Pair("Done is better than perfect.", "Sheryl Sandberg"),
        Pair("Do first things first, and second things not at all.", "Peter Drucker"),
        Pair("You can do anything, but not everything.", "David Allen"),
        Pair("Efficiency is doing things right; effectiveness is doing the right things.", "Peter Drucker"),
        Pair("Be crucial to your own success. Focus, plan, and execute.", "Unknown"),
        Pair("Quality is not an act, it is a habit.", "Aristotle"),
        Pair("Start where you are. Use what you have. Do what you can.", "Arthur Ashe"),
        Pair("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
        Pair("It always seems impossible until it's done.", "Nelson Mandela"),
        Pair("One of the secrets of getting things done is to make a to-do list every day.", "Richard Branson"),
        Pair("To-do lists help us break large projects into actionable bite-sized pieces.", "Unknown"),
        Pair("A year from now you may wish you had started today.", "Karen Lamb"),
        Pair("If you love life, don't waste time, for time is what life is made up of.", "Bruce Lee"),
        Pair("Lost time is never found again.", "Benjamin Franklin"),
        Pair("My goal is no longer to get more done, but rather to have less to do.", "Francine Jay"),
        Pair("You don't need more time in your day, you need more mind in your time.", "Kerry Gleeson"),
        Pair("The essence of self-discipline is to do the important thing rather than the urgent thing.", "Unknown"),
        Pair("If there are nine dogs in a track and you want to catch one, focus on one.", "Jack Ma"),
        Pair("Focus is a matter of deciding what things you're not going to do.", "John Carmack"),
        Pair("There is no waste in the world like the waste of a mind that is unfocused.", "Unknown"),
        Pair("Keep your mind on your objective, and do not be distracted by other things.", "Unknown"),
        Pair("Continuous improvement is better than delayed perfection.", "Mark Twain"),
        Pair("Ordinary people think merely of spending time. Great people think of using it.", "Arthur Schopenhauer"),
        Pair("An hour of planning can save you hours of doing.", "Unknown"),
        Pair("The critical ingredient is getting off your butt and doing something.", "Nolan Bushnell"),
        Pair("Do not wait; the time will never be 'just right.' Start where you stand.", "Napoleon Hill"),
        Pair("You may delay, but time will not.", "Benjamin Franklin"),
        Pair("Action is the antidote to anxiety.", "Unknown"),
        Pair("Work expands to fill the time available for its completion.", "Cyril Northcote Parkinson"),
        Pair("You can't build a reputation on what you are going to do.", "Henry Ford"),
        Pair("Big jobs usually go to the men who prove their ability to outgrow small ones.", "Theodore Roosevelt"),
        Pair("Motivation is what gets you started. Habit is what keeps you going.", "Jim Ryun"),
        Pair("Small daily improvements over time lead to stunning results.", "Robin Sharma"),
        Pair("If you are losing your leisure, look out! You may be losing your life.", "Virginia Woolf"),
        Pair("By failing to prepare, you are preparing to fail.", "Benjamin Franklin"),
        Pair("It's not that I'm so smart, it's just that I stay with problems longer.", "Albert Einstein"),
        Pair("Genius is 1% inspiration, 99% perspiration.", "Thomas Edison"),
        Pair("Don't wish it were easier. Wish you were better.", "Jim Rohn"),
        Pair("The structure of your day determines the productivity of your life.", "Unknown"),
        Pair("Great things are created by people who focus on the details.", "Unknown"),
        Pair("To focus means to bring all your energy to a single point.", "Unknown"),
        Pair("Simplify your life, amplify your focus.", "Unknown"),
        Pair("If you want an easy job to seem mighty hard, just keep putting off doing it.", "Olin Miller"),
        Pair("Procrastination is the thief of time.", "Edward Young"),
        Pair("The best way to get something done is to begin.", "Unknown"),
        Pair("Life is too short to spend it on things that don't matter.", "Unknown"),
        Pair("Make each day your masterpiece.", "John Wooden"),
        Pair("To be disciplined is to choose between what you want now and what you want most.", "Abraham Lincoln"),
        Pair("Focus on the process, not just the outcome.", "Unknown"),
        Pair("Productivity is being able to do things that you were never able to do before.", "Franz Kafka"),
        Pair("Time is a created thing. To say 'I don't have time' is to say 'I don't want to.'", "Lao Tzu"),
        Pair("Never mistake motion for action.", "Ernest Hemingway"),
        Pair("What we fear doing most is usually what we most need to do.", "Tim Ferriss"),
        Pair("Energy is the essence of life. Every day you decide how you're going to use it.", "Oprah Winfrey"),
        Pair("No project is ever too big if you break it into small, actionable steps.", "Unknown"),
        Pair("A clever person solves a problem. A wise person avoids it.", "Albert Einstein"),
        Pair("Be not afraid of going slowly, be afraid only of standing still.", "Chinese Proverb"),
        Pair("A journey of a thousand miles begins with a single step.", "Lao Tzu"),
        Pair("Your work is going to fill a large part of your life, do what you believe is great work.", "Steve Jobs"),
        Pair("Nothing is so fatiguing as the eternal hanging on of an uncompleted task.", "William James"),
        Pair("If you don't design your own life plan, chances are you'll fall into someone else's.", "Jim Rohn"),
        Pair("A plan is telling your tasks where to go instead of wondering where your day went.", "Unknown"),
        Pair("The bad news is time flies. The good news is you're the pilot.", "Michael Altshuler"),
        Pair("Time management is life management.", "Robin Sharma"),
        Pair("We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Will Durant"),
        Pair("The key to productivity is to do the absolute minimum amount of work to get the maximum result.", "Unknown"),
        Pair("Focus on the vital few and ignore the trivial many.", "Richard Koch"),
        Pair("Your future is created by what you do today, not tomorrow.", "Robert Kiyosaki"),
        Pair("If you want to live a happy life, tie it to a goal, not to people or things.", "Albert Einstein"),
        Pair("Success is the sum of small efforts, repeated day-in and day-out.", "Robert Collier"),
        Pair("The search for productivity is a search for clarity.", "Unknown"),
        Pair("Subtracting from your list is often more productive than adding.", "Unknown"),
        Pair("Don't count the days, make the days count.", "Muhammad Ali"),
        Pair("Productivity is the deliberate design of your daily habits.", "Unknown"),
        Pair("You are more than your output, but your output defines your footprint.", "Unknown"),
        Pair("Priorities are not things you have; they are things you do.", "Unknown"),
        Pair("Focus on depth, not just breadth.", "Unknown"),
        Pair("Make your focus so sharp that others can't help but notice.", "Unknown"),
        Pair("Action without planning is the cause of all failure.", "Alex Osborn"),
        Pair("Planning without action is completely futile.", "Unknown"),
        Pair("Concentrate on the correct path, and the destination will take care of itself.", "Unknown"),
        Pair("The secret of your future is hidden in your daily routine.", "Mike Murdock"),
        Pair("There is no shortcut to any place worth going.", "Beverly Sills"),
        Pair("He who is of calm and happy nature will hardly feel the pressure of age.", "Plato"),
        Pair("Calm mind brings inner strength and self-confidence, so that's very important for good health.", "Dalai Lama"),
        Pair("Only the focused mind can achieve true breakthroughs.", "Unknown"),
        Pair("Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"),
        Pair("Either you run the day, or the day runs you.", "Jim Rohn"),
        Pair("The best time to plant a tree was 20 years ago. The second best time is today.", "Chinese Proverb"),
        Pair("There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", "Colin Powell"),
        Pair("It is during our darkest moments that we must focus to see the light.", "Aristotle Onassis"),
        Pair("A goal without a plan is just a wish.", "Antoine de Saint-Exupéry"),
        Pair("Real productivity is about making progress, not just being active.", "Unknown"),
        Pair("Stop waiting for the perfect moment. Take the moment and make it perfect.", "Unknown"),
        Pair("A task left undone remains a weight on your mind.", "Unknown"),
        Pair("Mastering others is strength. Mastering yourself is true power.", "Lao Tzu"),
        Pair("Work hard in silence, let your success be your noise.", "Frank Ocean"),
        Pair("Don't stay in bed, unless you can make money in bed.", "George Burns"),
        Pair("The successful warrior is the average man, with laser-like focus.", "Bruce Lee"),
        Pair("If you have time to whine, you have time to find a solution.", "Dee Dee Artner")
    )

    fun getRandom(): Pair<String, String> {
        return list.random()
    }
}
